s

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -103,7 +103,7 @@ jobs:
       image: ghcr.io/afuetterer/rdmo-ci-image:latest
     strategy:
       matrix:
-        python-version: ['3.9', '3.13']
+        python-version: ['3.13']
         db-backend: [mysql, postgres]
     steps:
     - uses: actions/checkout@v4
@@ -154,147 +154,147 @@ jobs:
         fail-on-error: false
         allow-empty: true
 
-  test-e2e:
-    name: "End-to-end Test (Python: ${{ matrix.python-version }}, DB: ${{ matrix.db-backend }})"
-    needs: build-wheel
-    runs-on: ubuntu-24.04
-    strategy:
-      matrix:
-        python-version: ['3.13']
-        db-backend: [postgres]
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v5
-      with:
-        python-version: ${{ matrix.python-version }}
-        cache: pip
-    - name: Download wheel
-      uses: actions/download-artifact@v4
-      with:
-        name: wheel
-        path: dist
-    - name: Install Dependencies
-      run: |
-        sudo apt-get update && sudo apt install --yes pandoc texlive-latex-base texlive-latex-extra texlive-luatex librsvg2-bin
-        python -m pip install --upgrade pip
-    - name: Install rdmo[postgres] from wheel and start postgresql
-      run: |
-        python -m pip install "$(ls dist/*.whl)[ci,postgres]"
-        sudo systemctl start postgresql.service
-        pg_isready
-        sudo -u postgres psql --command="CREATE USER postgres_user PASSWORD 'postgres_password' CREATEDB"
-    - name: Prepare Env
-      run: |
-        cp -r testing/media testing/media_root && mkdir testing/log
-    - name: Install e2e tests dependencies
-      run: |
-        playwright install --with-deps chromium
-    - run: mkdir screenshots
-    - name: Collect static files into static root (only required if rdmo is installed from wheel)
-      run: python testing/manage.py collectstatic --noinput
-    - name: Run end-to-end tests
-      run: pytest -p randomly -p no:cacheprovider --reuse-db --numprocesses=auto --dist=loadscope -m e2e --nomigrations
-      env:
-        DJANGO_DEBUG: True
-        GITHUB_DB_BACKEND: ${{ matrix.db-backend }}
-    - uses: actions/upload-artifact@v4
-      with:
-        name: screenshots
-        path: screenshots/**/*.png
+  # test-e2e:
+  #   name: "End-to-end Test (Python: ${{ matrix.python-version }}, DB: ${{ matrix.db-backend }})"
+  #   needs: build-wheel
+  #   runs-on: ubuntu-24.04
+  #   strategy:
+  #     matrix:
+  #       python-version: ['3.13']
+  #       db-backend: [postgres]
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set up Python ${{ matrix.python-version }}
+  #     uses: actions/setup-python@v5
+  #     with:
+  #       python-version: ${{ matrix.python-version }}
+  #       cache: pip
+  #   - name: Download wheel
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: wheel
+  #       path: dist
+  #   - name: Install Dependencies
+  #     run: |
+  #       sudo apt-get update && sudo apt install --yes pandoc texlive-latex-base texlive-latex-extra texlive-luatex librsvg2-bin
+  #       python -m pip install --upgrade pip
+  #   - name: Install rdmo[postgres] from wheel and start postgresql
+  #     run: |
+  #       python -m pip install "$(ls dist/*.whl)[ci,postgres]"
+  #       sudo systemctl start postgresql.service
+  #       pg_isready
+  #       sudo -u postgres psql --command="CREATE USER postgres_user PASSWORD 'postgres_password' CREATEDB"
+  #   - name: Prepare Env
+  #     run: |
+  #       cp -r testing/media testing/media_root && mkdir testing/log
+  #   - name: Install e2e tests dependencies
+  #     run: |
+  #       playwright install --with-deps chromium
+  #   - run: mkdir screenshots
+  #   - name: Collect static files into static root (only required if rdmo is installed from wheel)
+  #     run: python testing/manage.py collectstatic --noinput
+  #   - name: Run end-to-end tests
+  #     run: pytest -p randomly -p no:cacheprovider --reuse-db --numprocesses=auto --dist=loadscope -m e2e --nomigrations
+  #     env:
+  #       DJANGO_DEBUG: True
+  #       GITHUB_DB_BACKEND: ${{ matrix.db-backend }}
+  #   - uses: actions/upload-artifact@v4
+  #     with:
+  #       name: screenshots
+  #       path: screenshots/**/*.png
 
-  coveralls:
-    name: Indicate completion to coveralls
-    needs: test
-    if: ${{ always() }}
-    runs-on: ubuntu-24.04
-    steps:
-    - name: Run Coveralls finish
-      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
-      with:
-        parallel-finished: true
-        fail-on-error: false
+  # coveralls:
+  #   name: Indicate completion to coveralls
+  #   needs: test
+  #   if: ${{ always() }}
+  #   runs-on: ubuntu-24.04
+  #   steps:
+  #   - name: Run Coveralls finish
+  #     uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
+  #     with:
+  #       parallel-finished: true
+  #       fail-on-error: false
 
-  dev-setup:
-    # Ref: structlog (MIT licensed) <https://github.com/hynek/structlog/blob/main/.github/workflows/ci.yml>
-    name: "Test dev setup on ${{ matrix.os }}"
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ubuntu-latest, windows-latest, macos-latest]
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-        with:
-          python-version: "3.13"
-          cache: pip
-      - run: python -Im pip install --editable .[dev]
-      - run: python -Ic 'import rdmo; print(rdmo.__version__)'
+  # dev-setup:
+  #   # Ref: structlog (MIT licensed) <https://github.com/hynek/structlog/blob/main/.github/workflows/ci.yml>
+  #   name: "Test dev setup on ${{ matrix.os }}"
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     matrix:
+  #       os: [ubuntu-latest, windows-latest, macos-latest]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         python-version: "3.13"
+  #         cache: pip
+  #     - run: python -Im pip install --editable .[dev]
+  #     - run: python -Ic 'import rdmo; print(rdmo.__version__)'
 
-  dependencies:
-    name: Test installation of all dependencies
-    needs: build-wheel
-    runs-on: ubuntu-24.04
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-        with:
-          python-version: "3.13"
-          cache: pip
-      - name: Download wheel
-        uses: actions/download-artifact@v4
-        with:
-          name: wheel
-          path: dist
-      - name: Install os requirements for python-ldap
-        run: sudo apt-get update && sudo apt-get install --yes libldap2-dev libsasl2-dev
-      - run: python -m pip install --upgrade pip
-      - name: Install rdmo wheel with all optional dependency groups
-        run: python -m pip install --no-compile "$(ls dist/*.whl)[allauth,ci,dev,gunicorn,ldap,mysql,postgres,pytest]"
-      - name: Verify installed packages have compatible dependencies
-        run: python -m pip check
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 22
-          cache: npm
-      - run: npm install --include=dev
-      - name: Write info to step summary
-        run: |
-          {
-            echo -e "# ✓ All dependency groups successfully installed in combination\n\n"
-            echo '<details><summary>Installed Python packages (dependency tree)</summary>'
-            echo -e "\n\`\`\`console"
-            echo "$ python -m pipdeptree --local-only --exclude=pip,pipdeptree"
-            python -m pipdeptree --local-only --exclude=pip,pipdeptree
-            echo -e "\`\`\`\n</details>"
-            echo '<details><summary>Outdated Python dependencies</summary>'
-            echo -e "\n\`\`\`console"
-            echo "$ python -m pip list --outdated"
-            python -m pip list --outdated
-            echo -e "\`\`\`\n</details>"
-            echo '<details><summary>Installed JavaScript packages (dependency tree)</summary>'
-            echo -e "\n\`\`\`console"
-            echo "$ npm list --all"
-            npm list --all
-            echo -e "\`\`\`\n</details>"
-            echo '<details><summary>Outdated JavaScript dependencies</summary>'
-            echo -e "\n\`\`\`console"
-            echo "$ npm outdated --long"
-            npm outdated --long || true
-            echo -e "\`\`\`\n</details>"
-          } >> $GITHUB_STEP_SUMMARY
+  # dependencies:
+  #   name: Test installation of all dependencies
+  #   needs: build-wheel
+  #   runs-on: ubuntu-24.04
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         python-version: "3.13"
+  #         cache: pip
+  #     - name: Download wheel
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: wheel
+  #         path: dist
+  #     - name: Install os requirements for python-ldap
+  #       run: sudo apt-get update && sudo apt-get install --yes libldap2-dev libsasl2-dev
+  #     - run: python -m pip install --upgrade pip
+  #     - name: Install rdmo wheel with all optional dependency groups
+  #       run: python -m pip install --no-compile "$(ls dist/*.whl)[allauth,ci,dev,gunicorn,ldap,mysql,postgres,pytest]"
+  #     - name: Verify installed packages have compatible dependencies
+  #       run: python -m pip check
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 22
+  #         cache: npm
+  #     - run: npm install --include=dev
+  #     - name: Write info to step summary
+  #       run: |
+  #         {
+  #           echo -e "# ✓ All dependency groups successfully installed in combination\n\n"
+  #           echo '<details><summary>Installed Python packages (dependency tree)</summary>'
+  #           echo -e "\n\`\`\`console"
+  #           echo "$ python -m pipdeptree --local-only --exclude=pip,pipdeptree"
+  #           python -m pipdeptree --local-only --exclude=pip,pipdeptree
+  #           echo -e "\`\`\`\n</details>"
+  #           echo '<details><summary>Outdated Python dependencies</summary>'
+  #           echo -e "\n\`\`\`console"
+  #           echo "$ python -m pip list --outdated"
+  #           python -m pip list --outdated
+  #           echo -e "\`\`\`\n</details>"
+  #           echo '<details><summary>Installed JavaScript packages (dependency tree)</summary>'
+  #           echo -e "\n\`\`\`console"
+  #           echo "$ npm list --all"
+  #           npm list --all
+  #           echo -e "\`\`\`\n</details>"
+  #           echo '<details><summary>Outdated JavaScript dependencies</summary>'
+  #           echo -e "\n\`\`\`console"
+  #           echo "$ npm outdated --long"
+  #           npm outdated --long || true
+  #           echo -e "\`\`\`\n</details>"
+  #         } >> $GITHUB_STEP_SUMMARY
 
-  required-checks-pass:
-    if: always()
-    needs:
-      - build-wheel
-      - test
-      - coveralls
-      - test-e2e
-      - dev-setup
-      - dependencies
-    runs-on: ubuntu-24.04
-    steps:
-      - uses: re-actors/alls-green@release/v1
-        with:
-          jobs: ${{ toJSON(needs) }}
+  # required-checks-pass:
+  #   if: always()
+  #   needs:
+  #     - build-wheel
+  #     - test
+  #     - coveralls
+  #     - test-e2e
+  #     - dev-setup
+  #     - dependencies
+  #   runs-on: ubuntu-24.04
+  #   steps:
+  #     - uses: re-actors/alls-green@release/v1
+  #       with:
+  #         jobs: ${{ toJSON(needs) }}
